
GET http://localhost:3000/api/v1/auth/register

### post
POST http://localhost:3000/api/v1/auth/register

{
    "username" : "uzumaki",
    "fullName" : "naruto uzumaki",
    "No_Hp" : "123434",
    "Password" : "12345"
}

### post
POST http://localhost:3000/api/v1/auth/login

{
    "username" : "uzumaki",
    "Password" : "12345"
}


